apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgresql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  volumeName: postgres-pv
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 2Gi 
