apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: postgres-db
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432