apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: backend
    releaseName: backend
    namespace: as-zadanie
    valuesFile: ./values.yaml
    additionalValuesFiles:
      - ../../base/values.yaml
  - name: frontend
    releaseName: frontend
    namespace: as-zadanie
    valuesFile: ./values.yaml
    additionalValuesFiles:
      - ../../base/values.yaml
  - name: postgres
    releaseName: postgres
    namespace: as-zadanie
    valuesFile: ./values.yaml
    additionalValuesFiles:
      - ../../base/values.yaml


patches:
  - target:
      kind: PersistentVolume
      name: postgres-pv
    patch: |-
      - op: replace
        path: /spec/capacity/storage
        value: 1Gi
  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi

      
      