apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: backend
    releaseName: backend
    namespace: as-zadanie
    valuesFile: ./values.yaml
    additionalValuesFiles:
      - ../../base/values.yaml
  - name: frontend
    releaseName: frontend
    namespace: as-zadanie
    valuesFile: ./values.yaml
    additionalValuesFiles:
      - ../../base/values.yaml
  - name: postgres
    releaseName: postgres
    namespace: as-zadanie
    valuesFile: ./values.yaml
    additionalValuesFiles:
      - ../../base/values.yaml
      