apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-js-frontend
        image: zadanie-frontend:1
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        resources:
          {{- include "res.limits" . | nindent 10 }}
